In [2]:
import numpy as np
import sys

In [3]:
a=np.array([1,2,3])
print(a)

[1 2 3]


In [9]:
b=np.array([[2,3,4],[34,66,6]],dtype='int16')
print(b)

[[ 2  3  4]
 [34 66  6]]


In [7]:
b.ndim

2

In [8]:
b.shape

(2, 3)

In [10]:
b.dtype

dtype('int16')

In [11]:
a.itemsize

8

In [12]:
b.itemsize

2

In [13]:
a.dtype

dtype('int64')

In [14]:
#a.nbytes=a.size*a.itemsize

a.size*a.itemsize

24

In [15]:
a.size

3

In [16]:
 a.nbytes

24

In [18]:
s=np.array([[14,45,5,6,66,54,3],[4,5,6,7,9,6,55]])
print(s)

[[14 45  5  6 66 54  3]
 [ 4  5  6  7  9  6 55]]


In [21]:
s[1,2]

6

In [22]:
s[0,:]

array([14, 45,  5,  6, 66, 54,  3])

In [24]:
s[0,1:6:2]

array([45,  6, 54])

In [26]:
s[1,5]=20

In [27]:
print(s)

[[14 45  5  6 66 54  3]
 [ 4  5  6  7  9 20 55]]


In [28]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [29]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [30]:
np.ones((4,2,2),dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [31]:
np.full((2,3),97)

array([[97, 97, 97],
       [97, 97, 97]])

In [33]:
np.full_like(s.shape,8)

array([8, 8])

In [34]:
np.full_like(s,8)

array([[8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8]])

In [37]:
np.random.rand(1,10)

array([[0.58427576, 0.47855109, 0.79120327, 0.90773118, 0.26507492,
        0.33563983, 0.77357118, 0.33825276, 0.06020035, 0.42109972]])

In [39]:
np.random.randint(1,78,size=(4,5))

array([[63, 49, 24, 69, 33],
       [31,  9, 31, 52, 34],
       [36, 54, 35,  4, 16],
       [32, 64, 36, 26, 62]])

In [40]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [43]:
arr=np.array([[1,2,3]])
r1=np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [44]:
o=np.ones((5,5))
print(o)
z=np.zeros((3,3))
z[1,1]=9
print(z)
o[1:-1,1:-1]=z
print(o)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [50]:
#COPY OF ARRAY
a=np.array([1,2,3])
# b=a
# b[0]=100
# print(b)
# print(a)

In [49]:
b=a.copy()
print(b)
print(a)

[1 2 3]
[1 2 3]


In [51]:
a=np.array([1,2,3])
print(a)

[1 2 3]


In [54]:
print(a+2)
print(a/2)
print(a**2)

[3 4 5]
[0.5 1.  1.5]
[1 4 9]


In [56]:
np.cos(a)
# np.sin(a)

array([0.84147098, 0.90929743, 0.14112001])

In [58]:
#LINEAR ALGEBRA
a=np.ones((2,3))
print(a)
b=np.full((3,2),2)
print(b)
#BEACOZ THE DIMENSION OF MATRIX IS DIFF
np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [60]:
c=np.identity(3)
np.linalg.det(c)

1.0

In [66]:
s=np.array([[1,2,3,4],[3,4,6,6]])
s


array([[1, 2, 3, 4],
       [3, 4, 6, 6]])

In [65]:
np.min(s)

1

In [67]:
np.max(s)

6

In [68]:
np.sum(s)

29

In [ ]:
#STACKING

In [70]:
v1=np.array([1,2,3,4])
v2=np.array([5,6,7,8])
np.vstack([v1,v2,v2,v1])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [1, 2, 3, 4]])

In [74]:
v1=np.array([1,2,3,4])
v2=np.array([5,6,7,8])
np.hstack([v1,v2])

array([1, 2, 3, 4, 5, 6, 7, 8])